version: 2.1

jobs:
  test-linux:
    docker:
      - image: cimg/base:current
    working_directory: /root/asdf-lein
    steps:
      - checkout
      - git clone https://github.com/asdf-vm/asdf.git asdf
      - . asdf/asdf.sh
      #- asdf plugin test <plugin-name> <plugin-url> [--asdf-tool-version <version>] [--asdf-plugin-gitref <git-ref>] [test-command*]
      #- asdf plugin test nodejs https://github.com/asdf-vm/asdf-nodejs.git node --version
      - asdf plugin test lein ${$CIRCLE_WORKING_DIRECTORY} 'lein --version'

  test-macos:
    macos:
      xcode: 14.2.0
    working_directory: /root/asdf-lein
    steps:
      - checkout
      - git clone https://github.com/asdf-vm/asdf.git asdf
      - . asdf/asdf.sh
      - asdf plugin test lein ${$CIRCLE_WORKING_DIRECTORY} 'lein --version'

workflows:
  test:
    jobs:
      - test-linux
      - test-macos
